<?php

function merken(){
	// een array van 50 merken! op te roepen via merken() overal in de code omdat regex_helper overal geladen wordt!
	$data = array(
			"Coca-Cola"		=>	"Coca-Cola",
			"Pepsi"			=> 	"Pepsi",
			"Fanta"			=>	"Fanta",
			"Sisi"			=>	"Sisi",
			"Albert Heijn"	=>	"Albert Heijn",
			"Jumbo"			=>	"Jumbo",
			"Lidl"			=>	"Lidl",
			"Aldi"			=>	"Aldi",
			"Prodent"		=>	"Prodent",
			"Coolfresh"		=>	"Coolfresh",
			"Lays"			=>	"Lays",
			"Pringles"		=>	"Pringles",
			"Netflix"		=>	"Netflix",
			"Nintendo"		=>	"Nintendo",
			"Playstation"	=>	"Playstation",
			"Sony"			=>	"Sony",
			"Android"		=>	"Android",
			"Apple"			=>	"Apple",
			"Samsung"		=>	"Samsung",
			"Microsoft"		=>	"Microsoft",
			"Efteling"		=>	"Efteling",
			"Walibi"		=>	"Walibi",
			"H&M"			=>	"H&M",
			"New Yorker"	=>	"New Yorker",
			"BBC"			=>	"BBC",
			"C&A"			=>	"C&A",
			"Primark"		=> 	"Primark",
			"V&D"			=>	"V&D",
			"Zeeman"		=>	"Zeeman",
			"Dirk"			=>	"Dirk",
			"Unox"			=>	"Unox",
			"Gilette"		=>	"Gilette",
			"Hema"			=>	"Hema",
			"Yamaha"		=>	"Yamaha",
			"BMW"			=>	"BMW",
			"Audi"			=>	"Audi",
			"Mazda"			=>	"Mazda",
			"Maybeline"		=>	"Maybeline",
			"Bijenkorf"		=>	"Bijenkorf",
			"Soho"			=>	"Soho",
			"M.A.C studio"	=>	"M.A.C. studio",
			"Axe"			=>	"Axe",
			"Dove"			=>	"Dove",
			"Nivea"			=>	"Nivea",
			"Ariel"			=>	"Ariel",
			"Robijn"		=>	"Robijn",
			"Gall & Gall"	=>	"Gall & Gall",
			"Alpaca"		=>	"Alpaca",
			"M&S mode"		=>	"M&S mode",
			"Levies"		=>	"Levies"
	);
	return randomize($data);
}
?>