<?php

function merken(){
	// een array van 50 merken! op te roepen via merken() overal in de code omdat regex_helper overal geladen wordt!
	$data = array(
			"Coca-Cola",
			"Pepsi",
			"Fanta",
			"Sisi",
			"Albert Heijn",
			"Jumbo",
			"Lidl",
			"Aldi",
			"Prodent",
			"Coolfresh",
			"Lays",
			"Pringles",
			"Netflix",
			"Nintendo",
			"Playstation",
			"Sony",
			"Android",
			"Apple",
			"Samsung",
			"Microsoft",
			"Efteling",
			"Walibi",
			"H&M",
			"New Yorker",
			"BBC",
			"C&A",
			"Primark",
			"V&D",
			"Zeeman",
			"Dirk",
			"Unox",
			"Gilette",
			"Hema",
			"Yamaha",
			"BMW",
			"Audi",
			"Mazda",
			"Maybeline",
			"Bijenkorf",
			"Soho",
			"M.A.C studio",
			"Axe",
			"Dove",
			"Nivea",
			"Ariel",
			"Robijn",
			"Gall & Gall",
			"Alpaca",
			"M&S mode",
			"Levies"
	);
	return randomize($data);
}
?>